/**
 * K-Life × Stellar — Setup Script
 * Creates two testnet wallets (agent + vault) and funds them via Friendbot
 */
const StellarSdk = require('@stellar/stellar-sdk');
const axios = require('axios');
const fs = require('fs');
const path = require('path');

async function fundAccount(publicKey) {
  console.log(`  💧 Funding ${publicKey} via Friendbot...`);
  await axios.get(`https://friendbot.stellar.org?addr=${publicKey}`);
  console.log(`  ✅ Funded!`);
}

async function main() {
  console.log('\n🎩 K-Life × Stellar — Testnet Setup\n');

  // Generate agent keypair
  const agentKeypair = StellarSdk.Keypair.random();
  console.log('🤖 Agent Wallet:');
  console.log(`   Public : ${agentKeypair.publicKey()}`);
  console.log(`   Secret : ${agentKeypair.secret()}`);
  await fundAccount(agentKeypair.publicKey());

  // Generate vault keypair
  const vaultKeypair = StellarSdk.Keypair.random();
  console.log('\n🏦 K-Life Vault Wallet:');
  console.log(`   Public : ${vaultKeypair.publicKey()}`);
  console.log(`   Secret : ${vaultKeypair.secret()}`);
  await fundAccount(vaultKeypair.publicKey());

  // Write .env file
  const envContent = `# K-Life × Stellar — Testnet Config
# Generated by setup.js

STELLAR_NETWORK=testnet
HORIZON_URL=https://horizon-testnet.stellar.org

AGENT_SECRET=${agentKeypair.secret()}
AGENT_NAME=Monsieur K

VAULT_ADDRESS=${vaultKeypair.publicKey()}

HEARTBEAT_INTERVAL_MS=30000
HEARTBEAT_AMOUNT=0.001
DEATH_TIMEOUT_MS=90000

X402_PORT=3402
X402_PRICE=0.001
`;

  fs.writeFileSync(path.join(__dirname, '../.env'), envContent);
  console.log('\n✅ .env file written!');
  console.log('\nNext steps:');
  console.log('  node src/agent.js    → start the agent (sends heartbeat micropayments)');
  console.log('  node src/monitor.js  → watch for agent death');
  console.log('  node src/x402-server.js → start x402 resurrection endpoint');
  console.log('  node src/demo.js     → run full demo sequence\n');
}

main().catch(console.error);
